#!/usr/bin/env osascript

-- gets tex expression as an
-- input and then puts it to LaTeXiT
on run argv
  set appName to "LaTeXiT"
  set latexExpr to item 1 of argv

  activate application appName

  tell application "System Events"
    tell front window of (process appName)
      set value of text area 1 of scroll area 1 of splitter group 1 of group 2 to latexExpr
      click radio button "Display" of radio group 1 of group 1 of group 2
      click button "LaTeX it!" of group 1 of group 2
      return "" -- suppress the output buy returning an empty string
    end tell
  end tell
end run
